_BASE_: '../COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x.yaml'
OUTPUT_DIR: train_outputs/kins_rcnn_rn101/
SOLVER:
  WEIGHT_DECAY: 0.0001
  BASE_LR: 0.02
  GAMMA: 0.1
  STEPS: (20000, 22000)
  MAX_ITER: 40000
  IMS_PER_BATCH: 4
DATALOADER:
  NUM_WORKERS: 8
SEED: 1
DATASETS:
  TRAIN:
  - kins_dataset_train
  TEST:
  - kins_dataset_val
TEST:
  EVAL_PERIOD: 0
